/**
 * Pre-build script for Electron packaging
 *
 * This script runs AFTER `next build` but BEFORE `electron-builder`.
 * It copies all necessary files into the .next/standalone directory
 * that Next.js doesn't automatically include.
 *
 * Usage: npx tsx scripts/prebuild.ts
 */

import fs from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const STANDALONE = path.join(ROOT, '.next', 'standalone')

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

function copyDir(src: string, dest: string) {
  ensureDir(path.dirname(dest))
  if (!fs.existsSync(src)) {
    console.warn(`[Prebuild] Source not found: ${src}`)
    return
  }
  fs.cpSync(src, dest, { recursive: true })
  console.log(`[Prebuild] Copied: ${path.relative(ROOT, src)} → ${path.relative(ROOT, dest)}`)
}

function copyFile(src: string, dest: string) {
  ensureDir(path.dirname(dest))
  if (!fs.existsSync(src)) {
    console.warn(`[Prebuild] Source not found: ${src}`)
    return
  }
  fs.copyFileSync(src, dest)
  console.log(`[Prebuild] Copied: ${path.relative(ROOT, src)} → ${path.relative(ROOT, dest)}`)
}

function main() {
  console.log('[Prebuild] Starting pre-build preparation...')

  if (!fs.existsSync(STANDALONE)) {
    console.error('[Prebuild] .next/standalone not found. Run `next build` first.')
    process.exit(1)
  }

  // 1. Copy static assets (CSS, JS, fonts)
  copyDir(
    path.join(ROOT, '.next', 'static'),
    path.join(STANDALONE, '.next', 'static'),
  )

  // 2. Copy public assets
  copyDir(
    path.join(ROOT, 'public'),
    path.join(STANDALONE, 'public'),
  )

  // 3. Copy Prisma schema and migrations
  copyFile(
    path.join(ROOT, 'prisma', 'schema.prisma'),
    path.join(STANDALONE, 'prisma', 'schema.prisma'),
  )
  copyDir(
    path.join(ROOT, 'prisma', 'migrations'),
    path.join(STANDALONE, 'prisma', 'migrations'),
  )

  // 4. Copy generated Prisma client
  copyDir(
    path.join(ROOT, 'src', 'generated'),
    path.join(STANDALONE, 'src', 'generated'),
  )

  // 4a. Remove the generated dir from standalone — it will be copied
  // from src/generated by extraResources in electron-builder.yml
  // This avoids EBUSY file lock issues during electron-builder copy
  fs.rmSync(path.join(STANDALONE, 'src', 'generated'), {
    recursive: true,
    force: true,
  })
  console.log('[Prebuild] Removed generated from standalone (copied via extraResources)')

  // 5. Copy skills (runtime prompt files)
  copyDir(
    path.join(ROOT, 'skills'),
    path.join(STANDALONE, 'skills'),
  )

  // 6. Copy prompts
  copyDir(
    path.join(ROOT, 'prompts'),
    path.join(STANDALONE, 'prompts'),
  )

  // 7. Copy config files
  copyFile(
    path.join(ROOT, 'package.json'),
    path.join(STANDALONE, 'package.json'),
  )
  copyFile(
    path.join(ROOT, 'prisma.config.ts'),
    path.join(STANDALONE, 'prisma.config.ts'),
  )

  // 8. Copy prisma CLI (not automatically included by standalone)
  copyDir(
    path.join(ROOT, 'node_modules', 'prisma'),
    path.join(STANDALONE, 'node_modules', 'prisma'),
  )
  copyDir(
    path.join(ROOT, 'node_modules', '@prisma'),
    path.join(STANDALONE, 'node_modules', '@prisma'),
  )

  // 9. Copy dotenv (used by prisma.config.ts)
  copyDir(
    path.join(ROOT, 'node_modules', 'dotenv'),
    path.join(STANDALONE, 'node_modules', 'dotenv'),
  )

  // 10. Create .env.local template if not exists
  const envTemplatePath = path.join(STANDALONE, '.env.local')
  if (!fs.existsSync(envTemplatePath)) {
    const template = `DATABASE_URL="file:./contentos.db"\n`
    fs.writeFileSync(envTemplatePath, template, 'utf-8')
    console.log('[Prebuild] Created .env.local template')
  }

  console.log('[Prebuild] Pre-build preparation complete!')
}

main()
